---
title: "Syllabus"
---

::: {.content-visible when-format="html"}
[**Click here**](syllabus.pdf) **to download a PDF copy of the syllabus.**
:::


## Course info

|           | Day       | Time              | Location |
|-----------|-----------|-------------------|----------|
| Lecture   | Tuesday    | 14:15  - 15:45  |  108  |



## Learning objectives

Gain experience in data collection and data analysis while working on problems and case studies inspired by and based on real-world questions. 

By the end of the semester, you will be able to obtain, explore, visualize, and analyze data using tools like Excel, Tableau and Microsoft PowerBI as well as SQL and Python.


## Where to get help

- If you have a question during lecture, feel free to ask it! 
- Outside of class, any general questions about course content or assignments should be posted on the Moodle course forum.
- Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include the name of our course in the subject line.** 

Check out the [Support](course-support.qmd) page for more resources.



### Exams {#sec-exams}

There will be one E-exam in Moodle:


- E-Exam (90 minutes at the end of the semester. 60% market research and 40% statistics)


More details about the exams will be given during the semester.


