---
title: "Market Research"
subtitle: "Course Overview"
---

Welcome to our course Market Research (337094)! ðŸ‘‹  


This page contains a weekly overview about the topics, slides and materials for the semester.

- [Moodle-course](https://moodle.hdm-stuttgart.de/course/view.php?id=2464#section-0)
- [Miro board ðŸ“](https://miro.com/app/board/uXjVNair5iM=/) (password is provided in Moodle)


:::{.callout-note}
This overview will be updated as the semester progresses.
:::

|	Nr.	|	Date	|	Topic	|	Literature	|		Resources		|	Links	|	
|	---	|	---	|	---	|	---	|		---		|	---	|	
|	1	|		|	**Introduction**	|		|				|		|	
|	2	|	10.10.	|	Business Model Canvas	|	[ðŸ“š](https://www.strategyzer.com/library/the-business-model-canvas)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1QVuajnvWqzBT9qnm2moNr5pVvH6G8LXmez8LOsA6lYc/export/pdf)		|		|	
|	3	|	10.10.	|	Data driven	|		|		[ðŸ“‘](https://docs.google.com/presentation/d/1AfzqhjEAfJ5X4Q8YC9GK14jEBfdDXEIRmXonriwYHNY/export/pdf)		|		|	
|	4	|		|	**Data Preparation and Analysis**	|		|				|		|	
|	5	|	10.10.	|	Market analysis lab (introduction)	|		|		[ðŸ’»](https://kirenz.github.io/lab-market-analysis)		|	[ðŸ“](https://forms.gle/s8G72dqiTPV58nCN6)	|	
|	6	|	17.10.	|	Market analysis lab 	|		|		[ðŸ’»](https://kirenz.github.io/lab-market-analysis)		|		|	
|	7	|	17.10.	|	How to obtain data	|		|		[ðŸ“‘](https://docs.google.com/presentation/d/1zldRDAOqmjoJmY_D4-ZkWfhwaklt-UfAPKH4G5kmFVY/export/pdf)		|		|	
|	8	|	24.10.	|	Pandas introduction lab (1 and 2)	|	[ðŸ“š](https://pandas.pydata.org/docs/)	|		[ðŸ’»](https://kirenz.github.io/lab-pandas-intro)		|		|	
|	9	|	31.10.	|	Pandas introduction lab (3 to 5)	|	[ðŸ“š](https://pandas.pydata.org/docs/)	|		[ðŸ’»](https://kirenz.github.io/lab-pandas-intro)		|		|	
|	10	|	07.11.	|	Pandas introduction lab (6 to 7)	|	[ðŸ“š](https://pandas.pydata.org/docs/)	|		[ðŸ’»](https://kirenz.github.io/lab-pandas-intro)		|		|	
|	11	|	07.11.	|	Lab Survey: Data prep (not relevant for exam)	|		|		[ðŸ’»](https://kirenz.github.io/lab-survey)		|		|	
|	12	|	14.11.	|	Lab Survey: Analysis	|		|		[ðŸ’»](https://kirenz.github.io/lab-survey)		|		|	
|	13	|		|	**Data Storytelling Part I**	|		|				|		|	
|	14	|	21.11.	|	The importance of context	|		|		[ðŸ“‘](https://docs.google.com/presentation/d/1XXsxfPoo2kCCnR8FZ6Bs4CGpfx81_vck-VY2C7meEOM/export/pdf)		|		|	
|	15	|	21.11.	|	Context: Back to school sale case study	|		|		[ðŸ“‘](https://docs.google.com/presentation/d/1_jGHyu0aKsQk7jxOmHgscreCrfcqrp9WbQdtWyg087o/export/pdf)		|		|	
|	16	|	21.11.	|	Narrow your audience exercise	|		|		[ðŸ“](https://docs.google.com/document/d/1Eu21TCIM0Lx6LiybPG-15ikk0gkRaqbCQNtcl3fAfGQ/edit?usp=sharing)		|		|	
|	17	|	21.11.	|	Storyboard exercise	|		|		[ðŸ“](https://docs.google.com/document/d/1WeLzE85YfM-F9-vAIhEbeJHkuHsN3xtovzIokB93BRU/edit?usp=sharing)		|		|	
|	18	|	21.11.	|	Display data in Excel	|	[ðŸ“Š Data](https://docs.google.com/spreadsheets/d/1DqBYgHGRhbORrw6FOLQPhv8ukm0TgM4C_HzzCXEgckw/edit?usp=sharing)	|		[ðŸ“‘](https://docs.google.com/presentation/d/12R3bTZvhj4drvjdQDjgUqk9a0LdAeUSZtELQIkt2ewM/export/pdf)		|		|	
|	19	|	28.11.	|	Excel exercises	|	[ðŸ“Š Data](https://docs.google.com/spreadsheets/d/1DqBYgHGRhbORrw6FOLQPhv8ukm0TgM4C_HzzCXEgckw/edit?usp=sharing)	|				|		|	
|	20	|	05.12.	|	Excel Ãœbung Marketing Kampagnen	|	[ðŸ“Š Data](https://docs.google.com/spreadsheets/d/1FDUDpOJSeg1n54PYXDVnBPQC66V1GZ9yeEEUT5TVwA8/edit?usp=sharing)	|		[ðŸ“‘](https://docs.google.com/presentation/d/149CFjlTAYFwX6_H2Dsc4SVtZC4tGg2AJl5Am-4fkhUQ/export/pdf)		|		|	
|	21	|	12.12.	|	Excel Ãœbung E-Commerce	|	[ðŸ“Š Data](https://docs.google.com/spreadsheets/d/1F4vu0e8mFmN0QZvZXhpFoFutBZNLWbj-Zzakdr0D-6w/edit?usp=sharing)	|		[ðŸ“‘](https://docs.google.com/presentation/d/17LSCPejdBgcJCFYx5QCOVmgFBakTg3twhHoTRHQR2s4/export/pdf)		|		|	
|	22	|	12.12.	|	Excel Ãœbung E-Commerce 2	|	[ðŸ“Š Data](https://docs.google.com/spreadsheets/d/1yE24B62VUdMMOsJYOIg5N3ZxXXm0h9mdmBftO7_gEV8/edit?usp=sharing)	|		[ðŸ“‘](https://docs.google.com/presentation/d/17cg9Fh2sY3ZFNzsy0NRgVpFhF6myQAF5yBmgyamB6TY/export/pdf)		|		|	
|	23	|		|	**Study Design**	|		|				|		|	
|	24	|	19.12.	|	Population and sample	|	[ðŸ“š](https://openintro-ims.netlify.app/data-design.html#data-design)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1QPdxp5sFumf9zee-WypsuzSkY7n_hvkhFsdJkRF3-pw/export/pdf)		|	[â˜‘ï¸](https://forms.gle/qPYg55ncRyUGCqXH8)	|	
|	25	|	19.12.	|	Sampling methods	|	[ðŸ“š](https://openintro-ims.netlify.app/data-design.html#sampling-principles-strategies)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1Rby9NR9F8pu1xHka0Xt1vvbH-oDRfrFC-bwb49IbhA8/export/pdf)		|	[â˜‘ï¸](https://forms.gle/SnQsTPKF5CRQ1Wa49)	|	
|	26	|	19.12.	|	Experiments	|	[ðŸ“š](https://openintro-ims.netlify.app/data-design.html#experiments)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1FTNBLYBCId2qsL1sMJf3qgBtaFH3hpbUm8lPck5BaTQ/export/pdf)		|	[â˜‘ï¸](https://forms.gle/6Tu92Ez83XANW8Un6)	|	
|	27	|	19.12.	|	Observational Studies	|	[ðŸ“š](https://openintro-ims.netlify.app/data-design.html#observational-studies)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1Oz5T_nuO1UFcjbliFmsEQWxG1dKJHDPPNWDeTvukxbE/export/pdf)		|	[â˜‘ï¸](https://forms.gle/V36KmsTjeH2finms9)	|	
|	28	|		|	**Classification**	|		|				|		|	
|	29	|	09.01.	|	Classification	|		|		[ðŸ“‘](https://docs.google.com/presentation/d/1Uait12xIaTM9rdyxSEnzIbR8opENnoOOPefuPocze3s/export/pdf)		|		|	
|	30	|	09.01.	|	Precision recall and F1 score	|	[ðŸ“š](https://mlu-explain.github.io/precision-recall/)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1X3_Ju8egEA8GwH_r76rxHHoC7tvHt8tMWXyT9WKfUko/export/pdf)		|		|	
|	31	|	09.01.	|	ROC Curve and AUC	|	[ðŸ“š](https://mlu-explain.github.io/roc-auc/)	|		[ðŸ“‘](https://docs.google.com/presentation/d/1wapuNTe4wVBUZVmH_X6-OxZlWkQL_YkhHsqZttQUWZk/export/pdf)	-->	|		|	
|	32	|	16.01.	|	Data splitting	|		|	<!--	[ðŸ“‘](https://docs.google.com/presentation/d/16DAGzUTUzI_prncqDeZx2HhpNnM_xTOL_Na0xTaDeVk/export/pdf)	-->	|		|	
|	33	|		|	**Inference**	|		|	<!--		-->	|		|	
|	34	|	16.01.	|	Hypothesis testing	|	[ðŸ“š](https://openintro-ims.netlify.app/foundations-randomization.html)	|	<!--	[ðŸ“‘](https://docs.google.com/presentation/d/1dhTaUlY3rjhBhUcTSL3Pf708DT3jCDQtrnlflACI1a8/export/pdf)	-->	|		|	
|	35	|	16.01.	|	P-value and significance	|	[ðŸ“š](https://openintro-ims.netlify.app/foundations-randomization.html#p-value-and-statistical-significance)	|	<!--	[ðŸ“‘](https://docs.google.com/presentation/d/1WObu30GH9KkutJ11tsAHnFWSNga3DfQyoIJoZM8S2TI/export/pdf)	-->	|		|	
|	36	|	16.01.	|	Decision errors	|	[ðŸ“š](https://openintro-ims.netlify.app/decerr.html)	|	<!--	[ðŸ“‘](https://docs.google.com/presentation/d/1ei-Tt6pqpPl_5oiMDMA9Coavf3ksCauxsJx2oK4U6L0/export/pdf)	-->	|		|	